server:
  port: 8080
  host: "0.0.0.0"

database:
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "root"
    database: "mcp_test"
    charset: "utf8mb4"
    parse_time: true
    loc: "Local"
  # 传统查询配置
  tables:
    user_table: "mcp_user" # 用户表名

mcp:
  server_url: "ws://localhost:8081/" # MCP服务器WebSocket地址 (连接到8081端口)
  timeout: 60s # 请求超时时间（适当增加，避免长响应导致超时）
  database:
    alias: "mysql_test"
    driver: "mysql"
    dsn: "root:root@tcp(localhost:3306)/mcp_test?charset=utf8mb4&parseTime=true&loc=Local"

# AI工具全局配置
ai:
  # 默认回答语言：zh-CN(中文)、en-US(英文)、auto(自动检测)
  response_language: "zh-CN"
  # 默认AI提供商和模型
  default_provider: "ollama"
  default_model: "codellama:7b"
  # 是否在请求中包含语言指令
  include_language_instruction: true
